const constants = {
    ADD_ITEM: 'ADD_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    EDIT_ITEM: 'EDIT_ITEM',
    FETCH_DATA: 'FETCH_DATA',
    FETCH_DATA_STARTED: 'FETCH_DATA_STARTED',
    FETCH_DATA_SUCCEED: 'FETCH_DATA_SUCCEED',
    FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',
};

export default constants;
